name: Android Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          key: buildozer-cache-${{ runner.os }}-${{ hashFiles('contrib/android/**', 'setup.py', 'requirements.txt') }}
          path: |
            .buildozer_qml
          restore-keys: |
            buildozer-cache-${{ runner.os }}-

      - name: Build Docker Image
        run: |
          docker build \
            -t electrum-android-builder-img \
            --file contrib/android/Dockerfile \
            .

      - name: Build Android APK
        run: |
          mkdir -p .buildozer_qml/.gradle
          docker run --rm \
            -v "$(pwd)":/home/user/wspace/electrum \
            -v "$(pwd)/.buildozer_qml/.gradle":/home/user/.gradle \
            --workdir /home/user/wspace/electrum \
            electrum-android-builder-img \
            ./contrib/android/make_apk.sh qml arm64-v8a debug

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: dist/*.apk
